package model

import (
	"crypto/rand"
	"encoding/json"
	"errors"
	"fmt"
	"log/slog"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"time"

	"github.com/siyuan-note/siyuan/kernel/conf"
	iroh_ffi "github.com/siyuan-note/siyuan/kernel/model/iroh"
	"github.com/siyuan-note/siyuan/kernel/util"
)

// IrohSwarmNode represents the local Iroh P2P Node and Swarm manager
type IrohSwarmNode struct {
	NodeKey     string
	Ticket      string
	DocTicket   string // The doc ticket string (generated by Share) for others to join
	mu          sync.Mutex
	onlinePeers []string
	priorityList []string

	irohNode   *iroh_ffi.Iroh
	irohDoc    *iroh_ffi.Doc
	irohAuthor *iroh_ffi.AuthorId

	// Lock state
	lockOwner string
	lockMu    sync.Mutex
}

var globalIrohNode *IrohSwarmNode

var (
	irohSyncDebounceTimer *time.Timer
	irohSyncDebounceMu    sync.Mutex
)

type irohSubscriber struct{}

func (s *irohSubscriber) Event(event *iroh_ffi.LiveEvent) *iroh_ffi.CallbackError {
	if event != nil && event.Type() == iroh_ffi.LiveEventTypeInsertRemote {
		remote := event.AsInsertRemote()
		if remote.Entry != nil {
			keyStr := string(remote.Entry.Key())
			// Ignore lock-sync and internal gossip keys to prevent infinite sync loops
			if keyStr == "lock-sync" || strings.HasPrefix(keyStr, "_siyuan_") {
				return nil
			}
		}

		irohSyncDebounceMu.Lock()
		if irohSyncDebounceTimer != nil {
			irohSyncDebounceTimer.Stop()
		}
		// Debounce: trigger sync 2 seconds after the last remote insert event
		irohSyncDebounceTimer = time.AfterFunc(2*time.Second, func() {
			slog.Info("Iroh: triggered auto-sync due to remote inserts")
			SyncData(false)
		})
		irohSyncDebounceMu.Unlock()
	}
	return nil
}

func InitIrohNode(ticket string) *IrohSwarmNode {
	if globalIrohNode != nil {
		return globalIrohNode
	}

	// Ensure config with stable secret key
	if Conf.Sync.Iroh == nil {
		Conf.Sync.Iroh = &conf.Iroh{DeviceNames: make(map[string]string)}
	}
	if len(Conf.Sync.Iroh.SecretKey) != 32 {
		Conf.Sync.Iroh.SecretKey = make([]byte, 32)
		rand.Read(Conf.Sync.Iroh.SecretKey)
		Conf.Save()
	}

	// Use persistent storage in the workspace so docs survive restarts
	irohDataPath := filepath.Join(util.WorkspaceDir, "temp", "iroh")
	if err := os.MkdirAll(irohDataPath, 0755); err != nil {
		panic("Failed to create Iroh data dir: " + err.Error())
	}

	secretKey := Conf.Sync.Iroh.SecretKey
	iNode, err := iroh_ffi.IrohPersistentWithOptions(irohDataPath, iroh_ffi.NodeOptions{
		EnableDocs: true,
		SecretKey:  &secretKey,
	})
	if err != nil {
		panic("Failed to init Iroh node: " + err.Error())
	}

	// Get or create author identity (persisted on disk now)
	authors, err := iNode.Authors().List()
	var author *iroh_ffi.AuthorId
	if err == nil && len(authors) > 0 {
		author = authors[0]
	} else {
		author, err = iNode.Authors().Create()
		if err != nil {
			panic("Failed to create author: " + err.Error())
		}
	}

	var doc *iroh_ffi.Doc
	var docTicketStr string

	// 1. If user joined another device's doc, that ticket is saved in Conf
	savedTicket := Conf.Sync.Iroh.Ticket
	if savedTicket != "" {
		docTicket, parseErr := iroh_ffi.NewDocTicket(savedTicket)
		if parseErr == nil {
			// Join is idempotent for already-known docs in the persistent store
			if joinedDoc, joinErr := iNode.Docs().Join(docTicket); joinErr == nil {
				doc = joinedDoc
				docTicketStr = savedTicket
				slog.Info("Iroh: opened/joined doc from saved ticket")
			} else {
				slog.Warn("Iroh: failed to join saved ticket, falling back to own doc", "err", joinErr)
			}
		}
	}

	// 2. Look for an existing own doc in the persistent store
	if doc == nil {
		if docList, listErr := iNode.Docs().List(); listErr == nil && len(docList) > 0 {
			if openedDoc, openErr := iNode.Docs().Open(docList[0].Namespace); openErr == nil && openedDoc != nil && *openedDoc != nil {
				doc = *openedDoc
				if sharedTicket, shareErr := doc.Share(iroh_ffi.ShareModeWrite, iroh_ffi.AddrInfoOptionsRelayAndAddresses); shareErr == nil {
					docTicketStr = sharedTicket.String()
				}
				slog.Info("Iroh: reusing existing persisted doc")
			}
		}
	}

	// 3. No existing doc found — create fresh
	if doc == nil {
		doc, err = iNode.Docs().Create()
		if err != nil {
			panic("Failed to create Iroh doc: " + err.Error())
		}
		if sharedTicket, shareErr := doc.Share(iroh_ffi.ShareModeWrite, iroh_ffi.AddrInfoOptionsRelayAndAddresses); shareErr == nil {
			docTicketStr = sharedTicket.String()
			slog.Info("Iroh: created new doc", "ticket", docTicketStr[:20]+"...")
		}
	}

	nodeId, _ := iNode.Node().Endpoint().NodeId()

	node := &IrohSwarmNode{
		NodeKey:      nodeId,
		Ticket:       savedTicket,
		DocTicket:    docTicketStr,
		irohNode:     iNode,
		irohDoc:      doc,
		irohAuthor:   author,
		onlinePeers:  []string{},
		priorityList: []string{},
	}
	globalIrohNode = node

	if doc != nil {
		doc.Subscribe(&irohSubscriber{})
	}

	go node.gossipLoop()
	return node
}

// Join connects to a remote doc ticket, replacing the current shared doc
func (n *IrohSwarmNode) Join(ticket string) error {
	if ticket == "" {
		return nil
	}

	docTicket, err := iroh_ffi.NewDocTicket(ticket)
	if err != nil {
		return fmt.Errorf("invalid ticket: %w", err)
	}

	doc, err := n.irohNode.Docs().Join(docTicket)
	if err != nil {
		return fmt.Errorf("failed to join swarm: %w", err)
	}

	n.mu.Lock()
	n.Ticket = ticket
	n.DocTicket = ticket
	n.irohDoc = doc
	n.onlinePeers = []string{}
	n.mu.Unlock()

	if doc != nil {
		doc.Subscribe(&irohSubscriber{})
	}

	return nil
}

// GetDocTicket returns a shareable write ticket for this node's document
func (n *IrohSwarmNode) GetDocTicket() (string, error) {
	n.mu.Lock()
	cached := n.DocTicket
	doc := n.irohDoc
	n.mu.Unlock()

	if cached != "" {
		return cached, nil
	}
	if doc == nil {
		return "", errors.New("doc not initialized")
	}

	ticket, err := doc.Share(iroh_ffi.ShareModeWrite, iroh_ffi.AddrInfoOptionsRelayAndAddresses)
	if err != nil {
		return "", errors.New(err.Error())
	}
	ticketStr := ticket.String()

	n.mu.Lock()
	n.DocTicket = ticketStr
	n.mu.Unlock()
	return ticketStr, nil
}

// Set stores data in the document
func (n *IrohSwarmNode) Set(key string, data []byte) error {
	n.mu.Lock()
	doc := n.irohDoc
	author := n.irohAuthor
	n.mu.Unlock()

	if doc == nil {
		return errors.New("doc not initialized")
	}
	_, setErr := doc.SetBytes(author, []byte(key), data)
	if setErr != nil {
		return errors.New(setErr.Error())
	}
	return nil
}

// Get retrieves data from the document (from any author, latest wins)
func (n *IrohSwarmNode) Get(key string) ([]byte, error) {
	n.mu.Lock()
	doc := n.irohDoc
	node := n.irohNode
	n.mu.Unlock()

	if doc == nil {
		return nil, errors.New("doc not initialized")
	}

	// Use cross-author query so any device's writes are visible
	query := iroh_ffi.QuerySingleLatestPerKeyExact([]byte(key))
	entry, queryErr := doc.GetOne(query)
	if queryErr != nil {
		return nil, errors.New(queryErr.Error())
	}
	if entry == nil || *entry == nil {
		return nil, fmt.Errorf("key not found")
	}

	hash := (*entry).ContentHash()
	data, readErr := node.Blobs().ReadToBytes(hash)
	if readErr != nil {
		return nil, errors.New(readErr.Error())
	}
	return data, nil
}

// Delete removes data from the document
func (n *IrohSwarmNode) Delete(key string) error {
	n.mu.Lock()
	doc := n.irohDoc
	author := n.irohAuthor
	n.mu.Unlock()

	if doc == nil {
		return nil
	}
	doc.Delete(author, []byte(key))
	return nil
}

// List returns all keys matching the prefix (across all authors, latest per key)
func (n *IrohSwarmNode) List(prefix string) ([]string, error) {
	n.mu.Lock()
	doc := n.irohDoc
	n.mu.Unlock()

	if doc == nil {
		return nil, nil
	}

	query := iroh_ffi.QuerySingleLatestPerKeyPrefix([]byte(prefix), nil)
	entries, queryErr := doc.GetMany(query)
	if queryErr != nil {
		return nil, errors.New(queryErr.Error())
	}

	var keys []string
	prefixLen := len(prefix)
	for _, entry := range entries {
		k := string(entry.Key())
		if len(k) > prefixLen {
			// Strip the prefix, matching what ListObjects callers expect
			keys = append(keys, k[prefixLen:])
		}
	}
	return keys, nil
}

// SyncPriorityList updates the priority list globally
func (n *IrohSwarmNode) SyncPriorityList(newList []string) error {
	n.mu.Lock()
	n.priorityList = newList
	n.mu.Unlock()

	data, err := json.Marshal(newList)
	if err != nil {
		return err
	}
	return n.Set("_siyuan_iroh_priority.json", data)
}

// getLeader determines the sync coordinator based on priority
func (n *IrohSwarmNode) getLeader() string {
	n.mu.Lock()
	defer n.mu.Unlock()

	if len(n.priorityList) == 0 {
		return n.NodeKey
	}

	for _, peer := range n.priorityList {
		if peer == n.NodeKey {
			return n.NodeKey
		}
		for _, op := range n.onlinePeers {
			if op == peer {
				return peer
			}
		}
	}
	return n.NodeKey
}

func (n *IrohSwarmNode) RequestLock() error {
	leader := n.getLeader()

	if leader == n.NodeKey {
		n.lockMu.Lock()
		if n.lockOwner != "" && n.lockOwner != n.NodeKey {
			n.lockMu.Unlock()
			return errors.New("lock already held by another node")
		}
		n.lockOwner = n.NodeKey
		n.lockMu.Unlock()
		return nil
	}

	// TODO: send RPC to leader for distributed lock
	return nil
}

func (n *IrohSwarmNode) ReleaseLock() error {
	leader := n.getLeader()
	if leader == n.NodeKey {
		n.lockMu.Lock()
		n.lockOwner = ""
		n.lockMu.Unlock()
	}
	return nil
}

func (n *IrohSwarmNode) gossipLoop() {
	for {
		time.Sleep(5 * time.Second)

		n.mu.Lock()
		doc := n.irohDoc
		node := n.irohNode
		nodeKey := n.NodeKey
		n.mu.Unlock()

		if doc == nil || node == nil {
			continue
		}

		// 1. Publish our current NodeAddr so other peers can find us
		status, statusErr := node.Node().Status()
		if statusErr != nil {
			continue
		}
		myAddr := status.NodeAddr()
		if myAddr != nil {
			addrInfo := map[string]interface{}{
				"nodeId":    nodeKey,
				"relay":     myAddr.RelayUrl(),
				"addresses": myAddr.DirectAddresses(),
			}
			if addrData, err := json.Marshal(addrInfo); err == nil {
				n.Set("_siyuan_iroh_addr_"+nodeKey, addrData)
			}
		}

		// 2. Collect peer NodeAddrs from the doc and call StartSync
		var peerAddrs []*iroh_ffi.NodeAddr
		peers, syncErr := doc.GetSyncPeers()
		if syncErr == nil && peers != nil {
			var activePeers []string
			for _, pBytes := range *peers {
				pubKey, pkErr := iroh_ffi.PublicKeyFromBytes(pBytes)
				if pkErr == nil {
					peerID := pubKey.String()
					activePeers = append(activePeers, peerID)

					// Read this peer's advertised address from the doc
					addrData, getErr := n.Get("_siyuan_iroh_addr_" + peerID)
					if getErr == nil && len(addrData) > 0 {
						var addrInfo struct {
							NodeId    string   `json:"nodeId"`
							Relay     *string  `json:"relay"`
							Addresses []string `json:"addresses"`
						}
						if json.Unmarshal(addrData, &addrInfo) == nil {
							peerAddr := iroh_ffi.NewNodeAddr(pubKey, addrInfo.Relay, addrInfo.Addresses)
							if peerAddr != nil {
								peerAddrs = append(peerAddrs, peerAddr)
							}
						}
					}
				}
			}
			n.mu.Lock()
			n.onlinePeers = activePeers
			n.mu.Unlock()
		}

		// Also read addresses from devices not yet in sync peers (bootstrap)
		// by checking all _siyuan_iroh_addr_* keys
		addrKeys, _ := n.List("_siyuan_iroh_addr_")
		for _, suffix := range addrKeys {
			peerID := suffix
			if peerID == nodeKey {
				continue // skip self
			}
			// Check if we already have this peer
			alreadyHave := false
			for _, pa := range peerAddrs {
				// Compare by checking direct addresses overlap
				if pa != nil {
					addrs := pa.DirectAddresses()
					if len(addrs) > 0 {
						alreadyHave = true
						break
					}
				}
			}
			if alreadyHave {
				continue
			}

			addrData, getErr := n.Get("_siyuan_iroh_addr_" + peerID)
			if getErr == nil && len(addrData) > 0 {
				var addrInfo struct {
					NodeId    string   `json:"nodeId"`
					Relay     *string  `json:"relay"`
					Addresses []string `json:"addresses"`
				}
				if json.Unmarshal(addrData, &addrInfo) == nil {
					pubKey, pkErr := iroh_ffi.PublicKeyFromString(peerID)
					if pkErr == nil {
						peerAddr := iroh_ffi.NewNodeAddr(pubKey, addrInfo.Relay, addrInfo.Addresses)
						if peerAddr != nil {
							peerAddrs = append(peerAddrs, peerAddr)
						}
					}
				}
			}
		}

		// 3. Force Iroh to sync with all known peers
		if len(peerAddrs) > 0 {
			if startErr := doc.StartSync(peerAddrs); startErr != nil {
				slog.Warn("Iroh: StartSync failed", "err", startErr, "peers", len(peerAddrs))
			}
		}

		// 4. Sync priority list from shared doc
		data, err := n.Get("_siyuan_iroh_priority.json")
		if err == nil {
			var list []string
			if json.Unmarshal(data, &list) == nil {
				n.mu.Lock()
				n.priorityList = list
				n.mu.Unlock()
			}
		}
	}
}

// GetSwarmState returns the current state for the UI
func (n *IrohSwarmNode) GetSwarmState() map[string]interface{} {
	n.mu.Lock()
	priorityList := n.priorityList
	onlinePeers := n.onlinePeers
	docTicket := n.DocTicket
	n.mu.Unlock()

	return map[string]interface{}{
		"nodeKey":      n.NodeKey,
		"docTicket":    docTicket,
		"priorityList": priorityList,
		"onlinePeers":  onlinePeers,
		"leader":       n.getLeader(),
	}
}
